# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-12 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('publish', models.CharField(max_length=32)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
