# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-12 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sites',
            new_name='Book',
        ),
    ]
